prepare configs for experiments

diff --git a/scripts/util/alpha_beta_75_25 b/scripts/util/alpha_beta_75_25
--- a/scripts/util/alpha_beta_75_25
+++ b/scripts/util/alpha_beta_75_25
@@ -3,7 +3,7 @@
 #SBATCH --output=job_output.txt
 #SBATCH --error=job_error.txt
 #SBATCH --ntasks=1
-#SBATCH --time=720:00
+#SBATCH --time=360:00
 #SBATCH --mem=100Gb
 
 source ~/.bashrc
@@ -17,11 +17,6 @@ conda install -c dglteam dgl-cuda11.1
 pip install -r requirements
 echo ""
 echo ""
-echo "TRAINING ORIGINAL:"
-python ./src/train.py --config ./config_files/psy/config_clst20_s47.json
-echo "TRAINING ORIGINAL: $?"
-echo ""
-echo ""
-echo "TRAINING SCALED:"
-python ./src/train.py --config ./config_files/psy/config_clst20_s47_alpha0.5_beta0.5.json
-echo "TRAINING SCALED: $?"
+echo "TRAINING ALPHA=0.75, BETA=0.25:"
+python ./src/train.py --config ./config_files/psy/config_clst20_s47_alpha0.75_beta0.25.json
+echo "ERROR CODE: $?"
