small changes

diff --git a/scripts/util/error_analysis b/scripts/util/error_analysis
--- a/scripts/util/error_analysis
+++ b/scripts/util/error_analysis
@@ -16,9 +16,5 @@ pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118
 conda install -c dglteam dgl-cuda11.1
 pip install -r requirements
 echo "GOT HERE"
-# python ./src/train.py --config ./config_files/cs/config_clst20_s47.json
-# echo "TRAIN: $?"
-python ./src/evaluate.py --config ./config_files_evaluate/cs/config_clst20_s47.json
-echo "EVAL ORIGINAL: $?"
-python ./src/evaluate.py --opt --config ./config_files_evaluate/cs/config_clst20_s47.json
-echo "EVAL OPTIMIZED: $?"
+python ./src/error_analysis.py --config ./config_files_evaluate/cs/config_clst20_s47.json
+echo "ERROR ANALYSIS: $?"
