prepare experiments

diff --git a/scripts/experiments/full_boundary_cs b/scripts/experiments/full_boundary_cs
--- a/scripts/experiments/full_boundary_cs
+++ b/scripts/experiments/full_boundary_cs
@@ -3,7 +3,7 @@
 #SBATCH --output=job_output.txt
 #SBATCH --error=job_error.txt
 #SBATCH --ntasks=1
-#SBATCH --time=5-05:00:00
+#SBATCH --time=1440:00
 #SBATCH --mem=100Gb
 
 source ~/.bashrc
@@ -15,9 +15,8 @@ conda activate taxocomplete
 pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 -f https://download.pytorch.org/whl/torch_stable.html
 conda install -c dglteam dgl-cuda11.1
 pip install -r requirements
-echo "GOT HERE"
-python ./src/evaluate.py --config ./config_files_evaluate/cs/config_clst20_s47.json
-python ./src/error_analysis.py data/MAG-CS-Wiki/trained/error_analysis.pkl
-python ./src/evaluate.py --config ./config_files_evaluate/cs/config_clst20_s47.json --untrained
-python ./src/error_analysis.py data/MAG-CS-Wiki/untrained/error_analysis.pkl
-echo "ERROR ANALYSIS: $?"
+echo ""
+echo ""
+echo "FULL BOUNDARY CS:"
+python ./src/train.py --config ./config_files/cs/full_boundary.json
+echo "ERROR CODE: $?"
