ready for experiments on CS with long tail

diff --git a/scripts/experiments/long_tail_abs_psy b/scripts/experiments/long_tail_abs_psy
--- a/scripts/experiments/long_tail_abs_psy
+++ b/scripts/experiments/long_tail_abs_psy
@@ -3,7 +3,7 @@
 #SBATCH --output=job_output.txt
 #SBATCH --error=job_error.txt
 #SBATCH --ntasks=1
-#SBATCH --time=720:00
+#SBATCH --time=1800:00
 #SBATCH --mem=100Gb
 
 source ~/.bashrc
@@ -15,7 +15,8 @@ conda activate taxocomplete
 pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 -f https://download.pytorch.org/whl/torch_stable.html
 conda install -c dglteam dgl-cuda11.1
 pip install -r requirements
-
-echo "EVAL HYPERBOLIC 1.0 PSY"
-python ./src/evaluate.py -c ./config_files_evaluate/psy/long_tail.json
-echo "EVAL HYPERBOLIC 1.0 PSY: $?"
+echo ""
+echo ""
+echo "LONG TAIL ABSOLUTE CS:"
+python ./src/train.py --config ./config_files/cs/long_tail_abs.json
+echo "ERROR CODE: $?"
